### ISSUE TITLE
Linode_Ip_List does not return a value.

### ISSUE THREAD

**Issue by PaulMDemers** [AustinWise/Austin.Linode#1]
Linode_Ip_List does not return any ip address that are in the JArray that GetResponse fetches.  The second argument in the function also appears to do nothing, it's an 'int?' which is just added to the request if not null.

My quick hack:
change the return type to object,  add a return statement to GetResponse and fetch "IPADDRESS" from the elements.

JArray o = (JArray)client.Linode_Ip_List(n.Id, null);
string ip = (string)o[0]["IPADDRESS"];

**Comment by AustinWise** [comment]
I pushed an commit that adds the return type for linode.ip.list. I also updated the generated code to include XML documentation comments from the Linode API Spec, so it should be more clear what there parameters to this function do.

I don't currently have any Linode instances running, so give it a shot and let me know how it works.

**Comment by AustinWise** [comment]
I also made a nuget package if that helps.

**Comment by PaulMDemers** [comment]
Just tested the fix and the nuget package, both work great thanks!
