### ISSUE TITLE
Linode_Disk_CreateFromImage returns void

### ISSUE THREAD

**Issue by drunkevich** [AustinWise/Austin.Linode#2]
I believe that method should return DiskIdResponse like other similar methods

UPD. same problem with Avail_Kernels

**Comment by AustinWise** [comment]
I uploaded a version that returns DiskIdResponse. However I have not set up my own testing environment. So if you get a chance, please let me know if it works.

**Comment by SoundAxis** [comment]
Tested, works.

**Comment by PaulMDemers** [comment]
Update: Doing some tests against the Linode API, seeing an issue with image.list returning empty arrays on the raw Linode API.

**Comment by AustinWise** [comment]
Is this still a problem? I created a new version of the [Nuget package](https://www.nuget.org/packages/Austin.Linode/) that should have the fix for this bug. See commit 67d1834ddda5b4176cd055f61a8a62d5ab622177.

**Comment by PaulMDemers** [comment]
Verified Linode_Disk_CreateFromImage working.

**Comment by AustinWise** [comment]
Thanks for checking it out.
