### ISSUE TITLE
How can I get the linodes list

### ISSUE THREAD

**Issue by RajuSPR** [AustinWise/Austin.Linode#3]
I had go through this API. But I don't know how can I get the linodes list. Which method I have to use and how to pass the parameters. Where I have to configure the personal access token. Please help me.

**Comment by AustinWise** [comment]
Please see the example called [IntegrationTest](https://github.com/AustinWise/Austin.Linode/blob/master/IntegrationTest/Program.cs)". I shows how to use to use the API, including getting a list of linodes.

**Comment by RajuSPR** [comment]
I had tried this integrationTest. And also passed my API token. But I got the response is "Authentication failed". How can I get the linodes list using the API token. Can you please explain with some screenshots. It will helpful for me.
![image](https://user-images.githubusercontent.com/48589501/58970441-174ab080-87d7-11e9-983e-1fc67e66f73f.png)

**Comment by AustinWise** [comment]
I noticed that for some reason the API keys created by the Linode console do not work. I pushed a new Nuget pack (0.5.1) that adds support for creating the `LinodeClient` object without the API key and then using the `user.getapikey` to create an API key using a user name and password:

```c#
var li = new LinodeClient();
string username = "...";
string password = "...";
var apiKey = await li.User_GetApiKeyAsync(password, username);
li.ApiKey = apiKey.Key;
var liNodes = await li.Linode_ListAsync();
```

BTW, this release also added `async` support.
